In [1]:
from sklearn.datasets  import load_iris ,load_breast_cancer

In [2]:
iris = load_iris()

In [3]:
from sklearn.linear_model import LogisticRegression

In [4]:
lr = LogisticRegression()

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
trainX,testX,trainY,testY = train_test_split(iris.data,iris.target)

In [7]:
lr.fit(trainX,trainY)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
lr.score(testX,testY)

1.0

In [10]:
lr.predict_proba(iris.data.data[144:146])

array([[  6.55755661e-04,   1.83504521e-01,   8.15839723e-01],
       [  1.62946288e-03,   2.58932303e-01,   7.39438234e-01]])

In [11]:
lr.coef_

array([[ 0.3809781 ,  1.37789184, -2.12112493, -0.98771126],
       [ 0.3012731 , -1.36854084,  0.57094664, -1.19565202],
       [-1.50101191, -1.34439455,  2.11542193,  2.29913249]])

In [ ]:
lr.intercept_ 

In [12]:
cancer_data= load_breast_cancer()

In [14]:
trainX,testX,trainY,testY = train_test_split(cancer_data.data,cancer_data.target )

In [15]:
lr.fit(trainX,trainY)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
lr.score(testX,testY)

0.95804195804195802

In [17]:
[cancer_data.data[0]]

[array([  1.79900000e+01,   1.03800000e+01,   1.22800000e+02,
          1.00100000e+03,   1.18400000e-01,   2.77600000e-01,
          3.00100000e-01,   1.47100000e-01,   2.41900000e-01,
          7.87100000e-02,   1.09500000e+00,   9.05300000e-01,
          8.58900000e+00,   1.53400000e+02,   6.39900000e-03,
          4.90400000e-02,   5.37300000e-02,   1.58700000e-02,
          3.00300000e-02,   6.19300000e-03,   2.53800000e+01,
          1.73300000e+01,   1.84600000e+02,   2.01900000e+03,
          1.62200000e-01,   6.65600000e-01,   7.11900000e-01,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01])]

In [18]:
lr.predict_proba(testX[:6])

array([[  6.41748309e-02,   9.35825169e-01],
       [  1.60242938e-01,   8.39757062e-01],
       [  9.93120146e-01,   6.87985415e-03],
       [  1.49299813e-02,   9.85070019e-01],
       [  9.99998548e-01,   1.45223522e-06],
       [  9.99999975e-01,   2.47799263e-08]])

In [19]:
lr.predict(testX[:5])

array([1, 1, 0, 1, 0])

In [20]:
testX[:5]

array([[  1.22700000e+01,   1.79200000e+01,   7.84100000e+01,
          4.66100000e+02,   8.68500000e-02,   6.52600000e-02,
          3.21100000e-02,   2.65300000e-02,   1.96600000e-01,
          5.59700000e-02,   3.34200000e-01,   1.78100000e+00,
          2.07900000e+00,   2.57900000e+01,   5.88800000e-03,
          2.31000000e-02,   2.05900000e-02,   1.07500000e-02,
          2.57800000e-02,   2.26700000e-03,   1.41000000e+01,
          2.88800000e+01,   8.90000000e+01,   6.10200000e+02,
          1.24000000e-01,   1.79500000e-01,   1.37700000e-01,
          9.53200000e-02,   3.45500000e-01,   6.89600000e-02],
       [  1.16300000e+01,   2.92900000e+01,   7.48700000e+01,
          4.15100000e+02,   9.35700000e-02,   8.57400000e-02,
          7.16000000e-02,   2.01700000e-02,   1.79900000e-01,
          6.16600000e-02,   3.13500000e-01,   2.42600000e+00,
          2.15000000e+00,   2.31300000e+01,   9.86100000e-03,
          2.41800000e-02,   4.27500000e-02,   9.21500000e-03,
       

In [34]:
import pandas as pd 
import numpy as np 

In [35]:
hr_data = pd.read_csv('HR_comma_sep.csv')

In [36]:
hr_data.head

<bound method NDFrame.head of        satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.

In [37]:
hr_data.sales.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [38]:
from sklearn.preprocessing import LabelEncoder


In [39]:
le = LabelEncoder()

In [40]:

hr_data['sales']=le.fit_transform(hr_data.sales)
hr_data['salary']=le.fit_transform(hr_data.salary)

In [42]:
f=hr_data.corr()['left']

In [44]:
imp_features = np.abs(f).sort_values(ascending = False).index.tolist()[1:5]

In [46]:
trainX,testX,trainY,testY=train_test_split(hr_data[imp_features],hr_data['left'])

In [47]:
lr.fit(trainX,trainY)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
lr.score(testX,testY)

0.77413333333333334

In [49]:
imp_features

['satisfaction_level',
 'Work_accident',
 'time_spend_company',
 'average_montly_hours']

In [50]:
trainX[:5]

satisfaction_level  Work_accident  time_spend_company  \
2169                 0.57              0                   2   
4947                 0.57              0                   4   
7444                 0.91              0                   2   
5786                 0.55              0                   2   
14559                0.11              0                   4   

       average_montly_hours  
2169                    142  
4947                    248  
7444                    239  
5786                    222  
14559                   264

In [55]:
lr.predict([[0.78,0,3,257]])

array([0], dtype=int64)

In [56]:
trainY[:5]

2169     0
4947     0
7444     0
5786     0
14559    1
Name: left, dtype: int64